#!/usr/bin/env bash
# In-container entry for the latest-wave run: seed the tui profile from the
# baked /seed/package.json (every @aiwayds plugin at its npm-latest version,
# generated by run-e2e-latest.sh), install from the OFFICIAL registry, then
# exec the scenario suite without 10-install (its subject — installing the
# source tarball — does not exist here; the profile is pre-seeded).
set -eu

PROFILE_DIR="$HOME/.dsh/profiles/tui"
printf '==> latest entry: seeding %s from /seed\n' "$PROFILE_DIR"
mkdir -p "$PROFILE_DIR"
cp /seed/package.json "$PROFILE_DIR/package.json"

# The official registry, explicitly: a just-published version may not be on
# the default mirror yet, and this run's whole point is what users get.
cd "$PROFILE_DIR"
pnpm install --registry=https://registry.npmjs.org
node -e '
const fs = require("fs")
const path = require("path")
const pkg = JSON.parse(fs.readFileSync(process.argv[1], "utf8"))
for (const [name, version] of Object.entries(pkg.dependencies)) {
  // Read from disk through the symlink — restrictive `exports` maps
  // (dsh-jev-core) do not expose ./package.json to require().
  const installed = JSON.parse(
    fs.readFileSync(path.join(process.argv[2], "node_modules", name, "package.json"), "utf8"),
  ).version
  if (installed !== version) {
    console.error(`version drift: ${name} pinned ${version}, installed ${installed}`)
    process.exitCode = 1
  }
  console.log(`  ${name}@${installed}`)
}
console.log("version check: every pinned dependency installed at its pin")
' "$PROFILE_DIR/package.json" "$PROFILE_DIR"

printf '==> running scenario suite (latest wave)\n'
cd /e2e/scenarios
# Taller pane for the full-wave startup tree (see common.sh), and the
# flag 50-resize-exit reads to soften its 80x24 whale check.
export TUI_ROWS=48
export E2E_FULL_WAVE=1
export E2E_SCENARIOS="20-start 22-search 30-commands 40-theme 50-resize-exit 60-preset 65-ux-batch 66-retention-resume 68-ask-user 69-btw 71-cache-hit 70-steer-injection 74-profiles 75-hard-stop 76-attention-early-stop 77-plugins-search"
exec bash /e2e/scenarios/run-all.sh
